name: check
on:
    push:
        branches: [main]
        tags:
            - "*"
    pull_request:
        branches: [main]
jobs:
    mac-build:
        runs-on: mac-arm
        env:
            CARGO_TARGET_DIR: ~/.cache/act/bearsays-mac-build/target
            PNPM_CACHE_FOLDER: ~/.cache/pnpm
            BINARY_NAME: bearsays
            ARCH: aarch64-apple-darwin
            FORGEJO_READWRITE_TOKEN: ${{ secrets.FORGEJO_READWRITE_TOKEN }}
        steps:
            - name: Check out repository code
              uses: actions/checkout@v4
            - name: Build
              run: |
                  (cd scripts && pnpm i)
                  node scripts/src/index.ts
    linux-build:
        runs-on: docker
        container:
            image: code.bearcove.cloud/bearcove/linux-builder:rust-1.85.0
            volumes:
                - /var/persistent-build-storage:/var/persistent-build-storage
            credentials:
                username: "token"
                password: "${{ secrets.BEARCOVE_PULL_PASSWORD }}"
        env:
            CARGO_TARGET_DIR: /var/persistent-build-storage/bearsays-linux-build/target
            PNPM_CACHE_FOLDER: /var/persistent-build-storage/pnpm-cache
            BINARY_NAME: bearsays
            ARCH: x86_64-unknown-linux-gnu
            FORGEJO_READWRITE_TOKEN: ${{ secrets.FORGEJO_READWRITE_TOKEN }}
        steps:
            - name: Check out repository code
              uses: actions/checkout@v4
            - name: Build
              run: |
                  (cd scripts && pnpm i)
                  node scripts/src/index.ts
