name: check
on:
    push:
        branches: [main]
        tags:
            - "*"
    pull_request:
        branches: [main]
jobs:
    mac-build:
        runs-on: mac-arm
        env:
            CARGO_TARGET_DIR: ~/.cache/act/bearsays-mac-build/target
        steps:
            - name: Check out repository code
              uses: actions/checkout@v4
            - name: Make sure cargo/rustup is installed
              run: |
                  cargo --version
            - name: Build
              run: |
                  echo "Building into ${CARGO_TARGET_DIR}"
                  mkdir -p ${CARGO_TARGET_DIR}
                  cargo build --verbose --release --timings
                  echo "Sweeping..."
                  cargo install cargo-sweep
                  echo "Size before:"
                  du -sh ${CARGO_TARGET_DIR}
                  cargo sweep --time 30
                  echo "Size after:"
                  du -sh ${CARGO_TARGET_DIR}
            - name: Upload timing results
              uses: actions/upload-artifact@v3
              with:
                  name: cargo-timing
                  path: ${CARGO_TARGET_DIR}/cargo-timings/cargo-timing.html
    linux-build:
        runs-on: docker
        container:
            image: code.bearcove.cloud/bearcove/earthly-ci:latest
            credentials:
                username: "fasterthanlime"
                password: "${{ secrets.BEARCOVE_PULL_PASSWORD }}"
        steps:
            - name: Check out repository code
              uses: actions/checkout@v4

            - name: Make sure cargo/rustup is installed
              run: |
                  cargo --version
            - name: Cache Cargo Build
              uses: https://code.forgejo.org/actions/cache@v3
              with:
                  path: target
                  key: ${{ runner.os }}-cargo-build-${{ hashFiles('**/Cargo.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-cargo-build-
            - name: Build
              run: |
                  cargo build --release
