name: pnpm-check
on:
    push:
jobs:
    pnpm-check:
        runs-on: mac-arm
        steps:
            - name: Check out repository code
              uses: actions/checkout@v4
            - name: Install dependencies
              run: |
                  pnpm -C scripts check
